### ISSUE TITLE
提供PDF MOBI 

### ISSUE THREAD

**Issue by wwek** [oopsguy/microservices-from-design-to-deployment-chinese#3]
RT
能集成gitbook 提供PDF MOBI 等电子书么, 方便Kindle阅读

**Comment by oopsguy** [comment]
@wwek 现在还在校对第二遍内容，尽量避免出现错别字和不通顺的地方，完成之后发布离线版本 ☺

**Comment by oopsguy** [comment]
@wwek 已经更新了PDF 和 MOBI 离线文件，可到 README 获取下载链接。
