### ISSUE TITLE
Any plans for english version?

### ISSUE THREAD

**Issue by pie6k** [oopsguy/microservices-from-design-to-deployment-chinese#4]
Seems it's great guide. Do you plan to translate it into other languages?

**Comment by oopsguy** [comment]
Hi, @pie6k . The guide was originally writen in English, and I just translated it into Chinese. You can get the English version from the nginx website 😊.

- [https://www.nginx.com/blog/introduction-to-microservices/](https://www.nginx.com/blog/introduction-to-microservices/)
- [https://www.nginx.com/resources/library/designing-deploying-microservices/](https://www.nginx.com/resources/library/designing-deploying-microservices/)
