### ISSUE TITLE
勘误：1.5、微服务的缺点

### ISSUE THREAD

**Issue by greatghoul** [oopsguy/microservices-from-design-to-deployment-chinese#7]
测试微服务应用程序也很复杂。例如，使用现代框架如 `Sprig Boot`，只需要编写一个测试类来启动一个单体 web 应用程序并测试其 REST API。

此处应为 Spring Boot 吧。

**Comment by oopsguy** [comment]
@greatghoul 感谢您的关注，这个错误在前几天的 PR #6  中已经修复了 。
